# Generated by Django 3.0.5 on 2020-04-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emulatorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=50)),
                ('hardwareName', models.CharField(max_length=50)),
                ('function_type', models.CharField(choices=[('S', 'Sensor'), ('A', 'Actuator')], max_length=1)),
                ('pin', models.IntegerField(default=-1)),
                ('valueType', models.CharField(max_length=10)),
                ('valueInteger', models.IntegerField(default=-1)),
                ('valueBoolean', models.BooleanField(default=False)),
                ('valueFloat', models.FloatField(default=-0.1)),
            ],
        ),
        migrations.RemoveField(
            model_name='function',
            name='device',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Function',
        ),
    ]
